name: Runner
on: 
  repository_dispatch
    #types: created
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - name: "${{ github.event.client_payload.build_name }} (${{ github.event.client_payload.build_id }})"
        uses: edersonbrilhante/gitlab-runner-action@main
        with:
          registration-token: "${{ github.event.client_payload.registration_token }}"
          docker-image: "docker:19.03.12"
          name: ${{ github.run_id }}
          tag-list: "gha, ubuntu"
