name: Docker runner
on: 
  repository_dispatch:
    types: created
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - name: Mask authentication token
        id: mask-authentication-token
        shell: bash
        run: echo "::add-mask::${{ github.event.client_payload.authentication_token }}"
      - name: "${{ github.event.client_payload.build_name }} (${{ github.event.client_payload.build_id }})"
        uses: edersonbrilhante/gitlab-runner-action@main
        with:
          registration-token: "${{ github.event.client_payload.authentication_token }}"
          docker-image: "docker:latest"
          name: ${{ github.run_id }}
          tag-list: "docker"
