name: Docker runner
on: 
  repository_dispatch:
    types: created
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - name: "${{ github.event.client_payload.build_name }} (${{ github.event.client_payload.build_id }})"
        uses: edersonbrilhante/gitlab-runner-action@main
        with:
          registration-token: "${{ secrets.AUTH_TOKEN_RUNNER_DOCKER }}"
          docker-image: "docker:latest"
          name: ${{ github.run_id }}
          tag-list: "docker"
